export const levels = {
  level1: [
    "pelota",
    "avion",
    "bailar",
    "color",
    "tierra",
    "dardo",
    "alma",
    "leche",
    "preso",
    "vivir",
  ],
  level2: [
    "cuchara",
    "bondad",
    "cocinar",
    "tocino",
    "esperar",
    "derrota",
    "salado",
    "aburrir",
    "marea",
    "aflojar",
  ],
  level3: [
    "terraza",
    "remolino",
    "leyenda",
    "enchufe",
    "altavoz",
    "asiento",
    "galaxia",
    "esparcir",
    "alacran",
    "numero",
  ],
  level4: [
    "localizar",
    "albondiga",
    "mentalizar",
    "taladrar",
    "prevenir",
    "carretera",
    "volumen",
    "atropellar",
    "nocturno",
    "ventana",
  ],
  level5: [
    "demolicion",
    "matematicas",
    "computadora",
    "cientifico",
    "remolacha",
    "garrapata",
    "componer",
    "revolucion",
    "universidad",
    "nacimiento",
  ],
  level6: [
    "involuntario",
    "espinacas",
    "cicatrizar",
    "continente",
    "turbulencia",
    "embarazo",
    "adolescente",
    "aplanadora",
    "telescopio",
    "insensible",
  ],
  level7: [
    "contaminacion",
    "propaganda",
    "mayordomo",
    "herramientas",
    "desarrollado",
    "estadisticas",
    "alternativa",
    "enfermedades",
    "trabajadores",
    "habitaciones",
  ],
  level8: [
    "extraterrestre",
    "correspondiente",
    "investigaciones",
    "administradores",
    "recomendaciones",
    "latinoamericana",
    "institucionales",
    "internacionales",
    "acontecimientos",
  ],
  level9: [
    "hemisferios",
    "supervivientes",
    "parlamentario",
    "revolucionario",
    "extraordinario",
    "comunicaciones",
    "contribuyente",
    "espectaculares",
    "modificadores",
  ],
  level10: [
    "tridimensional",
    "desproporcionado",
    "establecimiento",
    "infraestructura",
    "narcotraficante",
    "interpretacion",
    "limpiaparabrisas",
  ],
};


export const infolevel = [
  "Cada que pulsas una letra esta se bloqueara para que evites pulsarla de nuevo",
  "Cada que pulsas una letra esta se bloqueara para que evites pulsarla de nuevo",
  "Si pulsas una letra erronea no se bloqueara",
  "Si pulsas una letra erronea no se bloqueara",
  "Las vocales estaran bloqueadas hasta el turno 5",
  "Las vocales estaran bloqueadas hasta el turno 5",
  "Empiezas con la cabeza y el cuerpo del personaje",
  "Empiezas con la cabeza y el cuerpo del personaje",
  "Empiezas con la cabeza y el cuerpo del personaje y las vocales estaran bloqueadas hasta el turno 4",
];